name: apapane
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  freezed: ^2.4.6
  cloud_firestore: ^5.0.1
  freezed_annotation: ^2.4.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  intl: any
  image_picker: ^1.1.2
  dart_openai: ^5.1.0
  bordered_text: ^2.0.0
  flutter_screenutil: ^5.3.1
  flutter_riverpod: ^2.4.9
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_analytics: ^11.0.1
  google_fonts: ^6.2.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flash: ^3.1.0
  uuid: ^4.4.0
  flutter_svg: ^2.0.10+1
  firebase_storage: ^12.0.1
  firebase_crashlytics: ^4.0.1
  fluttertoast: ^8.2.4
  material_floating_search_bar: ^0.3.7
  json_serializable: ^6.7.1
  http: ^1.0.0
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1
  get: ^4.6.5
  flutter_chat_ui: ^1.6.13
  image_cropper: ^7.0.5
  flutter_chat_types: ^3.6.2
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6
  in_app_purchase_storekit: ^0.3.17
  package_info_plus: ^8.0.0
  go_router: ^14.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/apapane_icon_1.png
    - assets/images/end_story_image.png
    - assets/images/home_image.png
    - assets/images/archive_my_story.png
    - assets/images/circle_indicator_image.png
    - assets/images/public_stories_image.png
    #profileImages
    - assets/images/fairy.png
    - assets/images/dragon_boy.png
    - assets/images/girl_rabbit.png
    - assets/images/ninja.png
    - assets/images/pirates.png
    - assets/images/venture.png
    - assets/images/volt_boy.png
    #titlePictures
    - assets/images/arupaka.png
    - assets/images/pirate.png
    - assets/images/boy.png
    - assets/images/dragon.png
    - assets/images/dream.png
    - assets/images/rupan.png
    - assets/images/girl.png
    - assets/images/pretty_girl.png
    - assets/images/dog.png
    - assets/images/apapane_knight.png
    - assets/images/judge_background.jpeg
    - assets/images/update_profile_image.png
    - assets/images/premium.PNG
    - assets/images/kohaku.png

    #削除
    - assets/a.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/apapane_icon_1.png"

  fonts:
    - family: ZenMaruGothic
      fonts:
        - asset: fonts/Zen_Maru_Gothic/ZenMaruGothic-Regular.ttf
