// ignore_for_file: constant_identifier_names

enum EnvKey {
  FIREBASE_API_KEY,
  FIREBASE_ANDROID_API_KEY,
  FIREBASE_IOS_API_KEY,
  FIREBASE_PROJECT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_ANDROID_APP_ID,
  FIREBASE_IOS_APP_ID,
  FIREBASE_IOS_BUNDLE_ID,
  GOOGLE_WEB_SERVER_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID,
  GOOGLE_IOS_URL_SCHEME,
  SUPPORT_EMAIL,
  PRIVACY_POLICY_URL,
  TERMS_OF_SERVICE_URL,
}
