// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0d3yqEHfKSUE4-RW6VsP3iP-tw-c079M',
    appId: '1:235993211771:web:aae2b5f17f317e385bd3de',
    messagingSenderId: '235993211771',
    projectId: 'apapane-3cca0',
    authDomain: 'apapane-3cca0.firebaseapp.com',
    storageBucket: 'apapane-3cca0.appspot.com',
    measurementId: 'G-TG5VD5MQB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLyPpf7thJcwehhSfl6KIsj9kPOqNtsr8',
    appId: '1:235993211771:android:5d732311e63afb865bd3de',
    messagingSenderId: '235993211771',
    projectId: 'apapane-3cca0',
    storageBucket: 'apapane-3cca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB15GNWX-CtX6z3LEHZpALSPt1-NBIS9rE',
    appId: '1:235993211771:ios:fc96b8645bd823135bd3de',
    messagingSenderId: '235993211771',
    projectId: 'apapane-3cca0',
    storageBucket: 'apapane-3cca0.appspot.com',
    iosClientId: '235993211771-shigho6g5d60dgqgi12brtmvpbt7pep8.apps.googleusercontent.com',
    iosBundleId: 'com.example.apapane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB15GNWX-CtX6z3LEHZpALSPt1-NBIS9rE',
    appId: '1:235993211771:ios:cd08275e4bc8a1ce5bd3de',
    messagingSenderId: '235993211771',
    projectId: 'apapane-3cca0',
    storageBucket: 'apapane-3cca0.appspot.com',
    iosClientId: '235993211771-0c0ep1lpv6iu8hn7r68of0u3uapsemvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.apapane.RunnerTests',
  );
}
